from dotenv import load_dotenv
import os
from pathlib import Path
from openai import AzureOpenAI
from playsound3 import playsound

# -------------------------------------------------------
# Demo 2: Transcribe an Audio File to Text
#
# Uses gpt-4o-mini-transcribe via Azure OpenAI.
# Plays the audio file first so the class can hear it,
# then transcribes it and prints the result.
#
# Default input: speech.mp3 generated by script 6.
# You can also drop any .mp3 or .wav file in this folder
# and update AUDIO_FILE to point to it.
# -------------------------------------------------------
load_dotenv(Path(__file__).parent / ".env")

client = AzureOpenAI(
    azure_endpoint=os.getenv("AZURE_OPENAI_SPEECH_ENDPOINT"),
    api_key=os.getenv("AZURE_OPENAI_SPEECH_KEY"),
    api_version="2025-03-01-preview"
)

MODEL = "gpt-4o-mini-transcribe"
AUDIO_FILE = Path(__file__).parent / "speech.mp3"


def main():
    os.system("cls" if os.name == "nt" else "clear")
    print("=" * 50)
    print("   Demo 2: Transcribe an Audio File to Text")
    print("   Model: gpt-4o-mini-transcribe")
    print("=" * 50)

    if not AUDIO_FILE.exists():
        print(f"\nAudio file not found: {AUDIO_FILE}")
        print("Run script 6 first to generate speech.mp3, or place any audio file here.")
        return

    print(f"\nFile     : {AUDIO_FILE.name}")
    print("Playing audio...\n")
    playsound(str(AUDIO_FILE))

    print("Transcribing...\n")
    with open(AUDIO_FILE, "rb") as audio_file:
        transcription = client.audio.transcriptions.create(
            model=MODEL,
            file=audio_file,
            response_format="text"
        )

    print("=" * 50)
    print("Transcription:")
    print("=" * 50)
    print(transcription)


if __name__ == "__main__":
    main()
